const westernUsernames = [
	"Ace of Spurs",
	"Bandana Bob",
	"Big Red",
	"Billy the Kidder",
	"Biscuit Bessie",
	"Black Bartlett",
	"Black-Eyed Buck",
	"Blaze Blaze",
	"Bluebell Belle",
	"Bootsie Boots",
	"Bullwhip Bob",
	"Cactus Carol",
	"Calamity Joel",
	"Cattle Kate",
	"Cherokee Charlie",
	"Chuckwagon Chuck",
	"Cinnamon Cindy",
	"Coyote Cassie",
	"Deadly Dave",
	"Deputy Dale",
	"Diamond Dan",
	"Digger Dan",
	"Dixie Duke",
	"Doc Hollerin",
	"Dusty Dan",
	"El Diablo",
	"El Guapo",
	"El Loco",
	"Fancy Francine",
	"Fast Draw Fred",
	"Fiddlin' Frank",
	"Flapjack Frank",
	"Freckles",
	"Gatling Gunther",
	"Geronimo Jack",
	"Giddy-Up Gary",
	"Gila Monster",
	"Gunslinger Gus",
	"Hickory Harry",
	"High Noon Holly",
	"Hondo Kid",
	"Horse Thief Hank",
	"Hoss",
	"Hungry Hank",
	"Iron Horse Ike",
	"Jailbird Jack",
	"Jesse Jane",
	"Judge Judy",
	"Killer Kari",
	"Lady Luck",
	"Lariat Larry",
	"Lightning Lou",
	"Lil' Abner",
	"Lil' Sure Shot",
	"Lonesome Larry",
	"Lucky Lenny",
	"Mad Dog",
	"Marshal Matt",
	"Maverick Mike",
	"Mississippi Molly",
	"Mustang Mandy",
	"Nevada Ned",
	"Outlaw Oscar",
	"Pecos Pete",
	"Pistol Packin' Patty",
	"Prickly Pete",
	"Quickdraw Quinn",
	"Ranger Rick",
	"Rattlesnake Jake",
	"Rawhide Rex",
	"Red River Ray",
	"Rifleman Roy",
	"Rocky Road",
	"Rodeo Roper",
	"Rowdy Roy",
	"Rustler Ralph",
	"Saddleback Sam",
	"Sarsaparilla Sue",
	"Sawed-Off Sally",
	"Scarlet",
	"Shotgun Sarah",
	"Showdown Steve",
	"Six-Shooter Steve",
	"Skull Creek Slim",
	"Snakebite Sam",
	"Sniper Sally",
	"Sonora Slim",
	"Spurs Malone",
	"Stampede Sam",
	"Stagecoach Sue",
	"Stetson Steve",
	"Sunset Slim",
	"Tall Tex",
	"Tennessee Tom",
	"The Arizona Kid",
	"The Black Stallion",
	"The Duke",
	"The Gambler",
	"The Gunslinger",
	"The Lone Ranger",
	"The Marlboro Man",
	"The Outlaw",
	"The Sundance Kid",
	"Tombstone Ted",
	"Trail Boss",
	"Trigger Happy",
	"Tumbleweed Todd",
	"Two-Gun Tony",
	"Varmint",
	"Wild West Wendy",
	"Wyatt Earp",
	"Yosemite Sam"
];

export const randomWesternUsername = (): string => {
	const randomIndex = Math.floor(Math.random() * westernUsernames.length)
	return westernUsernames[randomIndex] || "Dusty Dan"
}